### PR TITLE
Added unit tests for dotnet core (xunit w/moq)

### PR DESCRIPTION
**Pull request by nickolasacosta**
I had to change a couple tests to work with xunit.

LinkTagCssSourceTest.ImplementsInterface()

Also added a constructor to CssSelectorParserTests.

```
cd PreMailer.Net\PreMailer.Net\PreMailer.Net.Core.Tests
dotnet test
```

All tests pass.

### CODE REVIEW

**Comment by martinnormark** [comment]
@nickolasacosta What does your Nu Get sources look like to make this work? I can't restore with the latest tooling, but perhaps my sources got messed up.

**Comment by nickolasacosta** [comment]
Nuget:
https://api.nuget.org/v3/index.json

Microsoft Visual Studio Offline Packages:
C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

**Comment by martinnormark** [comment]
Any chance you can target your PR into [`dotnet-core`](https://github.com/milkshakesoftware/PreMailer.Net/tree/dotnet-core) branch?

**Comment by nickolasacosta** [comment]
Sure I can, I meant to do that....

Is there a way to do it without recreating the request?

**Comment by martinnormark** [comment]
Afraid there's no way to change it. But I might already have your commits since I checked out this PR into my own branch and merged into dotnet-core so your exact commits should be included and maintained. 

I have a Mac with everything dotnet core set up, so I can have a look at that issue.

**Comment by nickolasacosta** [comment]
new PR inc.

**Pull request closed without merging**
