### PR TITLE
Access to underlying Document made public

### PR DESCRIPTION
**Pull request by neurospeech**

### CODE REVIEW

**Comment by neurospeech** [comment]
@martinnormark can you please push this on NuGet?

**Comment by martinnormark** [comment]
Just [tagged the release](https://github.com/milkshakesoftware/PreMailer.Net/releases/tag/v1.5.0) and Nu Get is now updated: https://www.nuget.org/packages/PreMailer.Net

**Comment by martinnormark** [comment]
Hey @neurospeech - does everything work with AngleSharp as expected?

**Comment by neurospeech** [comment]
Yes, thank you very much, it is very helpful now as I can do many operations just in one document instead of re-parsing it again. I had added small snippet in readme.md file. It works correctly.

**Comment by martinnormark** [comment]
:+1:

**Pull request merged**
