### PR TITLE
Replaced CsQuery with AngleSharp

### PR DESCRIPTION
**Pull request by burningice2866**
I've made sure that all the tests are succeeding, but haven't tested anything "in real life".

### CODE REVIEW

**Comment by burningice2866** [comment]
One think we could look at as well, is to replace the custom css parsing with AngleSharp, since it contains a proper CssParser.

**Comment by martinnormark** [comment]
Do you have an example of using the CssParser from AngleSharp?

I can't seem to find method to merge styles based on specificity, but I'm sure it's in there.

**Comment by martinnormark** [comment]
btw, thanks for submitting this contribution. Hugely appreciated! :bow:

**Comment by burningice2866** [comment]
@martinnormark Hey, had a pretty crazy week. I haven't had the chance to look much at the CssParser in AngleSharp yet, but will take a look when i get some time.

Thanks for the merge.

**Pull request merged**
