### PR TITLE
Add analytics tags using PreMailer

### PR DESCRIPTION
**Pull request by kendallb**
We are using PreMailer to inline our CSS, but also need to add Analytics tags. It is a lot more overhead per email to re-parse the entire HTML all over again with another instance of CsQuery to do the analytics tags processing, so it works faster if we moved our code for this into PreMailer. Plus I hope someone else will find this useful.

### CODE REVIEW

**Comment by martinnormark** [comment]
Thanks for this.

Can you improve the code formatting of your additions, please? Prefer to keep method definitions in one line, and it would be great if you could tab the indentions of your additions.

As to the concept of analytics, wouldn't it be convenient to opt in based on the target domain of the links? If you for some reason have links pointing to other sites than your own, you can avoid adding campaign parameters?

Specifying the domain in the `AddAnalyticsTags` method should be optional IMHO.

**Comment by kendallb** [comment]
Sure. I use resharper so I need to configure it different for your code.

For me personally we never have links in our emails to other domains but I can imagine if someone did that would be useful. It would add an extra overhead but maybe it could be optional and the default passed is null?

Sent from my iPhone

Kendall Bennett
CEO & Founder
www.AMain.com<http://www.amain.com/> | 530-894-0797<tel:530-894-0797> | 800-705-2215<tel:800-705-2215>
424 Otterson Drive, Chico, California 95928<x-apple-data-detectors://2/1>

On May 1, 2015, at 10:45 PM, Martin H. Normark <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for this.

Can you improve the code formatting of your additions, please? Prefer to keep method definitions in one line, and it would be great if you could tab the indentions of your additions.

As to the concept of analytics, wouldn't it be convenient to opt in based on the target domain of the links? If you for some reason have links pointing to other sites than your own, you can avoid adding campaign parameters?

Specifying the domain in the AddAnalyticsTags method should be optional IMHO.

**Comment by kendallb** [comment]
Ok, code is checked in. The domain checking handles domains without http:// in front, although I suspect anyone sending email will never have a relative URL in there, but it seemed safer that way.

Have you guys done any performance tuning on the code? The CSS inlining accounts for a large portion of our email rendering (actually most of it) but I have not yet taken a look to see where it spends all the time. If you have already spent a lot of time optimizing it I probably won’t bother looking into it ...

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by martinnormark** [comment]
:+1: Great

Can you revert 9f5fd9d50ac98acacdfe2f3469d2e83ce3aa2bb3 to avoid a breaking change, then I'll merge into master and push a new package to Nu Get.

**Comment by kendallb** [comment]
I made a couple of other changes in my tree related to performance that I am about to test...

But I am confused as to why that change would be a breaking change? The public API has not changed at all because the previous public entry point was this:

public static InlineResult MoveCssInline(string html, bool removeStyleElements = false, string ignoreElements = null, string css = null, bool stripIdAndClassAttributes = false)

Previously the constructor was private, and I made it public so I could create an instance and chain calls together as needed, but prior to that none of those functions were public until I made them. 

Unless it is something else I missed?

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by kendallb** [comment]
Ok, my performance changes are complete. The code originally had some bugs in such that it was incorrectly using the RegexOptions.Compiled flag (using an & rather than an |). I fixed that and notice a lot of other Regexes were not compiled so I change them all over. When I performance tested the new library, it ran about 25% of the speed of the non compiled Regexes! So I went and removed the compiled flag throughout the entire library but left my changes to move all the regexes into static variables so they can be reused (just not compiled) and voila, that runs about 4-5% faster than the prior library.

This was tested processing thousands of emails back to back and it was quite noticeable.

I think I am going to track down all the compiled regexes in my own code and get rid of them; I naturally assumed they would always be faster...

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by martinnormark** [comment]
My bad, didn't notice the method signature was the same.

Regarding the `Render` method, couldn't `MoveCssInline` do that to keep it consistent? Same method name to be called either static or instance method?

The flow would the look like this:

```
var pm = new PreMailer("html");
pm.AddAnalyticsTags(...);

var result = pm.MoveCssInline(...);
```

or like this:

```
var result = PreMailer.MoveCssInline(...);
```

What do you think?

**Comment by kendallb** [comment]
No because in my case I chain the two together. I do not want to render the results from the CsQuery document until I have also added the analytics tags. So in our code we are calling it like this:

                // Move the CSS inline
                var pm = new PreMailer.Net.PreMailer(htmlBody);
                MoveCssInline(pm);

                // Add anlaytics tracking tags to the HTML if not in test mode
                if (!newsletter.TestMode) {
                    AddAnalyticsTags(pm,
                        newsletter.Source,
                        newsletter.Campaign,
                        topLevelCategoryID);
                }

                // Render the resulting HTML
                htmlBody = pm.Render(DomRenderingOptions.RemoveComments).Html;

That way we don’t take the performance hit of rendering the HTML twice, which is what would happen if it was rendered in the MoveCssInline() method call.

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by martinnormark** [comment]
If `AddAnalyticsTags` merely stored the settings until you call `MoveCssInline` it wouldn't process the HTML twice.

That way everything leading up to a `MoveCssInline` call would be unobtrusive (just setting up the PM engine for processing a desired result).

I think that would be more clear and consistent.

**Comment by kendallb** [comment]
True, except how can I pass in the option to remove comments from the HTML when it is rendered? For that I would need to add more to the MoveCssInline signature. Although maybe others would use that option also if it was surfaced...

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by martinnormark** [comment]
Yes, it makes sense to put it in `MoveCssInline` as an optional parameter like the other parameters.

**Comment by kendallb** [comment]
Sounds like a plan. I will change it.

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by kendallb** [comment]
Ok, see what you think now. I removed the DomRenderingOptions completely and made it a boolean, so we don’t expose CsQuery internals through the public API.

Regards,

Kendall Bennett
CEO & Co-Founder
www.AMain.com | 530-894-0797 | 800-705-2215 
424 Otterson Drive, Chico, California 95928

**Comment by martinnormark** [comment]
:+1: Very nice! Thanks for submitting this PR, and doing the follow up work! Much appreciated!

**Pull request merged**
