### PR TITLE
Added support for link tags

### PR DESCRIPTION
**Pull request by zeus82**
Started over, to fix tab problem.  Now the diff only shows actual changes.

### CODE REVIEW

**Comment by zeus82** [comment]
Do you know when you'll have a chance to review this?

**Comment by martinnormark** [comment]
Sorry, forgot about it. Will do tonight. 

--
Martin H. Normark

**Comment by zeus82** [comment]
great - thanks!

**Comment by martinnormark** [comment]
Thanks for this :bow: 

Will write a few tests, and then push to Nu Get.

**Comment by martinnormark** [comment]
@zeus82 Sorry for the delay with pushing to Nu Get - it's live there now :neckbeard:

**Pull request merged**
